/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import Controles.LobbyController;

/**
 *
 * @author HP
 */
public class CrearSala extends javax.swing.JPanel {
    
    private int tamanhoSala = 0;
    
    /**
     * Creates new form CrearSala
     */
    public CrearSala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnContinuar = new javax.swing.JButton();
        tamanho4 = new javax.swing.JLabel();
        tamanho3 = new javax.swing.JLabel();
        tamanho2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 239, 225));
        setMaximumSize(new java.awt.Dimension(943, 640));
        setMinimumSize(new java.awt.Dimension(943, 640));
        setPreferredSize(new java.awt.Dimension(943, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNO_Log_pequenho.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Crear sala");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        BtnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 140, 40));

        BtnContinuar.setBackground(new java.awt.Color(51, 102, 255));
        BtnContinuar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        BtnContinuar.setText("Siguiente");
        add(BtnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, 180, 40));

        tamanho4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tamanho4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tamanho4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tamanho4.png"))); // NOI18N
        tamanho4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tamanho4MouseClicked(evt);
            }
        });
        add(tamanho4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 240, 360));

        tamanho3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tamanho3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tamanho3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tamanho3.png"))); // NOI18N
        tamanho3.setMaximumSize(new java.awt.Dimension(943, 680));
        tamanho3.setMinimumSize(new java.awt.Dimension(943, 680));
        tamanho3.setPreferredSize(new java.awt.Dimension(943, 680));
        tamanho3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tamanho3MouseClicked(evt);
            }
        });
        add(tamanho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 240, 360));

        tamanho2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tamanho2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tamanho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tamanho2.png"))); // NOI18N
        tamanho2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tamanho2MouseClicked(evt);
            }
        });
        add(tamanho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 270, 360));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Selecciona el tamaño de la sala");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tamanho4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamanho4MouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() <= 1){
            tamanhoSala = 4;
        }
        
    }//GEN-LAST:event_tamanho4MouseClicked

    private void tamanho3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamanho3MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() <= 1){
            tamanhoSala = 3;
        }
        
    }//GEN-LAST:event_tamanho3MouseClicked

    private void tamanho2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamanho2MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() <= 1){
            tamanhoSala = 2;
        }
    }//GEN-LAST:event_tamanho2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel tamanho2;
    private javax.swing.JLabel tamanho3;
    private javax.swing.JLabel tamanho4;
    // End of variables declaration//GEN-END:variables

    public void ListenerBtnSiguiente(ActionListener listener){
        BtnContinuar.addActionListener(listener);
    }
    public void ListenerBtnCancelar(ActionListener listener){
        BtnCancelar.addActionListener(listener);
    }
    public int getTamanhoSala(){
        return tamanhoSala;
    }
    public void setController(LobbyController controller){
        BtnContinuar.addActionListener(
            e -> controller.onContinueClicked()
        );
       BtnCancelar.addActionListener(
         e -> controller.onLeaveClicked()
       );
    }
    public void showError(String message) {
//        errorLabel.setText(message == null || message.isBlank() ? " " : message);
        JOptionPane.showMessageDialog(this, message);

    }

}
