/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import Controles.LobbyController;
import Dominio.Player;

/**
 *
 * @author HP
 */
public class SalaEspera extends javax.swing.JPanel {

    /**
     * Creates new form SalaEspera
     */
    private LobbyController controller;
    
    public SalaEspera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnIniciarPartida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelCodigoSala = new javax.swing.JLabel();
        PanelNumJugadores = new javax.swing.JPanel();
        labelNumJugadores = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PanelTamanhoSala = new javax.swing.JPanel();
        labelTamanhoSala = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelJugadores = new javax.swing.JPanel();
        BtnSalir = new javax.swing.JButton();
        BtnSolicitarIniciar = new javax.swing.JButton();
        BtnListo = new javax.swing.JButton();
        waitingStatusLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 239, 225));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnIniciarPartida.setBackground(new java.awt.Color(51, 102, 255));
        BtnIniciarPartida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnIniciarPartida.setForeground(new java.awt.Color(255, 255, 255));
        BtnIniciarPartida.setText("Iniciar Partida");
        add(BtnIniciarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Sala de espera");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNO_Log_pequenho.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 130));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("No. Jugadores:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        labelCodigoSala.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCodigoSala.setText("1234567");
        add(labelCodigoSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, -1, -1));

        PanelNumJugadores.setBackground(new java.awt.Color(242, 234, 229));
        PanelNumJugadores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        PanelNumJugadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNumJugadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNumJugadores.setText("1");
        PanelNumJugadores.add(labelNumJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        add(PanelNumJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 70, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tamaño de sala:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        PanelTamanhoSala.setBackground(new java.awt.Color(242, 234, 229));
        PanelTamanhoSala.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        PanelTamanhoSala.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTamanhoSala.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTamanhoSala.setText("4");
        PanelTamanhoSala.add(labelTamanhoSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        add(PanelTamanhoSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 70, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Codigo de Sala");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, -1, -1));

        panelJugadores.setBackground(new java.awt.Color(0, 87, 193));
        panelJugadores.setLayout(new javax.swing.BoxLayout(panelJugadores, javax.swing.BoxLayout.Y_AXIS));
        add(panelJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 790, 390));

        BtnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnSalir.setText("Salir");
        add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 110, 30));

        BtnSolicitarIniciar.setBackground(new java.awt.Color(255, 255, 153));
        BtnSolicitarIniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnSolicitarIniciar.setText("Solicitar Iniciar");
        add(BtnSolicitarIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, 180, 30));

        BtnListo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnListo.setText("Cancelar Listo");
        BtnListo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnListoMouseClicked(evt);
            }
        });
        add(BtnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, 160, 30));
        add(waitingStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnListoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnListoMouseClicked
        // TODO add your handling code here:
//         BtnListo.addActionListener(e -> controller.onReadyClicked());
    }//GEN-LAST:event_BtnListoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciarPartida;
    private javax.swing.JButton BtnListo;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSolicitarIniciar;
    private javax.swing.JPanel PanelNumJugadores;
    private javax.swing.JPanel PanelTamanhoSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel labelCodigoSala;
    public javax.swing.JLabel labelNumJugadores;
    public javax.swing.JLabel labelTamanhoSala;
    public javax.swing.JPanel panelJugadores;
    private javax.swing.JLabel waitingStatusLabel;
    // End of variables declaration//GEN-END:variables

    // ─────────────────────────────────────────────
    // Métodos que el Controller llama para actualizar la View
    // ─────────────────────────────────────────────
 
    /**
     * Actualiza la lista visual de jugadores conectados.
     * Redibuja toda la lista cada vez que cambia.
     *
     * @param players    Lista actual de jugadores.
     * @param localName  Nombre del jugador local (para resaltarlo).
     * @param isHost     Si el jugador local es Host.
     */
    public void updatePlayerList(List<Player> players, String localName, boolean isHost) {
        panelJugadores.removeAll();
 
        for (Player p : players) {
            JPanel row = buildPlayerRow(p, localName.equals(p.getName()), isHost);
            panelJugadores.add(row);
            panelJugadores.add(Box.createVerticalStrut(2));
        }
 
        panelJugadores.revalidate();
        panelJugadores.repaint();
    }
 
    /**
     * Construye la fila visual de un jugador en la lista del lobby.
     *
     * @param player   El jugador a mostrar.
     * @param isLocal  Si es el jugador local (se resalta diferente).
     * @param hostView Si el que ve esto es el Host.
     * @return El panel de la fila.
     */
    private JPanel buildPlayerRow(Player player, boolean isLocal, boolean hostView) {
        JPanel row = new JPanel(new BorderLayout(10, 0));
        row.setBackground(isLocal
            ? new Color(30, 58, 95)   // azul oscuro: soy yo
            : new Color(30, 35, 50)); // gris oscuro: otro jugador
        row.setBorder(new EmptyBorder(10, 14, 10, 14));
        row.setMaximumSize(new Dimension(Integer.MAX_VALUE, 55));
 
        // Ícono según rol: corona para Host, control para jugador normal
        String roleIcon = player.isHost() ? "👑" : "🎮";
        // Etiqueta de rol visible para todos
        String roleLabel = player.isHost() ? " [HOST]" : "";
        String youLabel  = isLocal ? " (tú)" : "";
 
        JLabel nameLabel = new JLabel(
            roleIcon + " " + player.getName() + roleLabel + youLabel
        );
        nameLabel.setFont(new Font("Arial", Font.BOLD, 14));
        // El Host tiene color dorado para destacarlo
        nameLabel.setForeground(player.isHost()
            ? new Color(248, 216, 71)
            : Color.WHITE);
 
        // Estado "Listo": refleja el valor real de player.isReady()
        // El Host puede estar listo o no listo como cualquier otro jugador
        JLabel readyLabel = new JLabel(player.isReady() ? "✅ Listo" : "⏳ Esperando");
        readyLabel.setFont(new Font("Arial", Font.PLAIN, 13));
        readyLabel.setForeground(player.isReady()
            ? new Color(74, 222, 128)
            : new Color(148, 163, 184));
        readyLabel.setHorizontalAlignment(SwingConstants.RIGHT);
 
        row.add(nameLabel,  BorderLayout.WEST);
        row.add(readyLabel, BorderLayout.EAST);
 
        return row;
    }
 
    /**
     * Actualiza el código de sala visible en el encabezado.
     *
     * @param code El código de la sala (ej. "A3F2-9KX1").
     */
    public void setRoomCode(String code) {
        labelCodigoSala.setText(code);
    }
 
    /**
     * Actualiza el contador de jugadores conectados.
     *
     * @param current  Cuántos hay ahora.
     * @param capacity Cuántos caben en total.
     */
    public void setPlayerCount(int current, int capacity) {
        labelNumJugadores.setText( current + "/" + capacity);
        labelTamanhoSala.setText(capacity+"");
    }
    
 
    /**
     * Habilita o deshabilita el botón "Iniciar Partida".
     * Solo el Host puede verlo habilitado, y solo cuando todos están listos.
     *
     * @param enabled {@code true} para habilitar.
     */
    public void setStartEnabled(boolean enabled) {
        BtnIniciarPartida.setEnabled(enabled);
    }
 
    /**
     * Configura la visibilidad del botón de inicio y el selector de capacidad
     * según si el jugador local es Host o Peer.
     *
     * @param isHost {@code true} si el jugador local es el Host.
     */
    public void configureForRole(boolean isHost) {
        BtnIniciarPartida.setVisible(isHost);
        BtnListo.setVisible(true);
        BtnSolicitarIniciar.setVisible(!isHost);
        revalidate();
        repaint();
        
//        capacitySelector.setEnabled(isHost); creo que este no lo ocuparemos si no 
                                            // traer la info desde la pantalla de crear sala
    }

    public void setWaitingStatus(String text) {
        waitingStatusLabel.setText(text);
    }

    
    /**
     * Habilita o deshabilita el botón "Solicitar Inicio".
     * Se habilita cuando el Peer ya marcó "Listo".
     *
     * @param enabled {@code true} para habilitar.
     */
    public void setRequestStartEnabled(boolean enabled) {
        BtnSolicitarIniciar.setEnabled(enabled);
    }

    /**
     * Muestra un diálogo al Host notificando que un Peer solicita iniciar.
     *
     * @param requesterName Nombre del Peer que hizo la solicitud.
     * @return {@code true} si el Host acepta iniciar.
     */
    public boolean showStartRequestDialog(String requesterName) {
        int result = JOptionPane.showConfirmDialog(
            this,
            requesterName + " solicita iniciar la partida ahora.\n¿Deseas iniciar con los jugadores actuales?",
            "Solicitud de inicio",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        return result == JOptionPane.YES_OPTION;
    }
 
    /**
     * Cambia el texto del botón "Listo" según el estado actual.
     *
     * @param isReady {@code true} si el jugador ya está listo.
     */
    public void updateReadyButton(boolean isReady) {
        BtnListo.setText(isReady ? "✗ Cancelar Listo" : "✓ Estoy Listo");
        BtnListo.setBackground(isReady
            ? new Color(71, 85, 105)
            : new Color(34, 197, 94));
    }
 
    // ─────────────────────────────────────────────
    // Registro del Controller
    // ─────────────────────────────────────────────
 
    /**
     * Asigna el Controller y conecta los listeners de los botones.
     *
     * @param controller El Controller de esta pantalla.
     */
    public void setController(LobbyController controller) {
        this.controller = controller;
 
        BtnListo.addActionListener(e -> controller.onReadyClicked());
        BtnIniciarPartida.addActionListener(e -> controller.onStartClicked());
        BtnSolicitarIniciar.addActionListener(e -> controller.onRequestStartClicked());
        BtnSalir.addActionListener(e -> controller.onLeaveClicked());
//        capacitySelector.addActionListener(e ->
//            controller.onCapacityChanged((Integer) capacitySelector.getSelectedItem())
//        );
    }

}
