/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author HP
 */
public class SalaEspera extends javax.swing.JPanel {

    /**
     * Creates new form SalaEspera
     */
    public SalaEspera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJugadores = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigoSala = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelTamanhoSala = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labellNumJugadores = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 239, 225));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaJugadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Avatar", "Usuario", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaJugadores);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 800, 380));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar Partida");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 180, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Sala de espera");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNO_Log_pequenho.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 130));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("No. Jugadores:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        codigoSala.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        codigoSala.setText("1234567");
        add(codigoSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, -1, -1));

        jPanel1.setBackground(new java.awt.Color(242, 234, 229));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTamanhoSala.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTamanhoSala.setText("1");
        jPanel1.add(labelTamanhoSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 70, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tamaño de sala:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        jPanel2.setBackground(new java.awt.Color(242, 234, 229));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labellNumJugadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labellNumJugadores.setText("4");
        jPanel2.add(labellNumJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 70, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Codigo de Sala");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel codigoSala;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labelTamanhoSala;
    public javax.swing.JLabel labellNumJugadores;
    public javax.swing.JTable tablaJugadores;
    // End of variables declaration//GEN-END:variables
}
