package Vistas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import Controles.RegisterController;

public class MenuPrincipal extends javax.swing.JPanel {

    private String avatarSeleccionado;
    private static final String[] AVATAR_IDS = {
        "avatar_pig", "avatar_bear", "avatar_panda", "avatar_bunny",
        "avatar_fox", "avatar_penguin", "avatar_chick", "avatar_wolf", "avatar_frog"
    };

    /**
     * Emojis usados para representar los avatares en texto (mientras no hay
     * imágenes).
     */
    private static final String[] AVATAR_EMOJIS = {
        "🐷", "🐻", "🐼", "🐰", "🦊", "🐧", "🐥", "🐺", "🐸"
    };
    private int selectedAvatarIndex = -1;
    private final JButton[] avatarButtons;
    private RegisterController controller;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        this.avatarButtons = new JButton[AVATAR_IDS.length];
        initComponents();
        PanelAvatars.add(buildAvatarPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorLabel = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnContinuar = new javax.swing.JButton();
        PanelAvatars = new javax.swing.JPanel();

        setBackground(new java.awt.Color(242, 239, 225));
        setMaximumSize(new java.awt.Dimension(943, 613));
        setMinimumSize(new java.awt.Dimension(943, 613));
        setPreferredSize(new java.awt.Dimension(943, 613));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 410, 170));

        campoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campoUsuarioMouseExited(evt);
            }
        });
        add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 450, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNO_Logo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 260, 220));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Selecciona tu avatar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre de Jugador");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        BtnContinuar.setBackground(new java.awt.Color(255, 0, 0));
        BtnContinuar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        BtnContinuar.setText("Continuar");
        add(BtnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 170, 40));

        PanelAvatars.setBackground(new java.awt.Color(242, 218, 179));
        PanelAvatars.setLayout(new javax.swing.BoxLayout(PanelAvatars, javax.swing.BoxLayout.X_AXIS));
        add(PanelAvatars, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 700, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoUsuarioMouseExited
        // TODO add your handling code here:
        //agregar bordo gris

    }//GEN-LAST:event_campoUsuarioMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnContinuar;
    private javax.swing.JPanel PanelAvatars;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void listenerBtnContinuar(ActionListener listener) {
        BtnContinuar.addActionListener(listener);
    }

    public void setAvatar(String a) {
        this.avatarSeleccionado = a;

    }

    public String getAvatarSeleccionado() {
        return avatarSeleccionado;
    }

    // ─────────────────────────────────────────────
    // Métodos que el Controller llama para actualizar la View
    // ─────────────────────────────────────────────
    private JPanel buildAvatarPanel() {
        JPanel panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 8, 4));
        panel.setBackground(new Color(242, 218, 179));

        for (int i = 0; i < AVATAR_EMOJIS.length; i++) {
            final int index = i;
            JButton btn = new JButton(AVATAR_EMOJIS[i]);
            btn.setFont(new Font("Segoe UI Emoji", Font.PLAIN, 20));
            btn.setPreferredSize(new Dimension(60, 60));
            btn.setBackground(new Color(242, 234, 218));
            btn.setBorderPainted(true);
            btn.setFocusPainted(false);
            btn.setToolTipText("Avatar " + (i + 1));

            // Al hacer clic, seleccionar este avatar
            btn.addActionListener(e -> {
                if (controller != null) {
                    controller.onAvatarSelected(index);
                }
            });

            avatarButtons[i] = btn;
            panel.add(btn);
        }

        return panel;
    }

    /**
     * Resalta el avatar seleccionado y quita el resaltado de los demás. El
     * Controller llama a esto cuando el usuario hace clic en un avatar.
     *
     * @param index El índice del avatar seleccionado.
     */
    public void highlightAvatar(int index) {
        selectedAvatarIndex = index;
        for (int i = 0; i < avatarButtons.length; i++) {
            if (i == index) {
                // Borde dorado para el seleccionado
                avatarButtons[i].setBackground(new Color(248, 216, 71));
                avatarButtons[i].setBorder(
                        BorderFactory.createLineBorder(new Color(248, 216, 71), 3));
            } else {
                avatarButtons[i].setBackground(new Color(51, 51, 72));
                avatarButtons[i].setBorder(UIManager.getBorder("Button.border"));
            }
        }
    }

    /**
     * Muestra un mensaje de error debajo del campo de nombre. Pasa cadena vacía
     * o " " para limpiar el error.
     *
     * @param message El mensaje de error a mostrar.
     */
    public void showError(String message) {
//        errorLabel.setText(message == null || message.isBlank() ? " " : message);
        JOptionPane.showMessageDialog(this, message);

    }

    /**
     * Marca un avatar como "en uso" (ya elegido por otro jugador). Lo
     * deshabilita visualmente para que el usuario no lo seleccione.
     *
     * @param avatarId El identificador del avatar a deshabilitar.
     */
    public void markAvatarTaken(String avatarId) {
        for (int i = 0; i < AVATAR_IDS.length; i++) {
            if (AVATAR_IDS[i].equals(avatarId)) {
                avatarButtons[i].setEnabled(false);
                avatarButtons[i].setToolTipText("En uso por otro jugador");
                avatarButtons[i].setBackground(new Color(30, 30, 46));
            }
        }
    }

    // ─────────────────────────────────────────────
    // Datos que el Controller lee de la View
    // ─────────────────────────────────────────────
    /**
     * Devuelve el texto ingresado en el campo de nombre. El Controller lo usa
     * para validar antes de continuar.
     *
     * @return El nombre ingresado, sin espacios extremos.
     */
    public String getPlayerName() {
        return campoUsuario.getText().trim();
    }

    /**
     * Devuelve el identificador del avatar actualmente seleccionado.
     *
     * @return El ID del avatar, o {@code null} si no hay ninguno seleccionado.
     */
    public String getSelectedAvatarId() {
        if (selectedAvatarIndex < 0) {
            return null;
        }
        return AVATAR_IDS[selectedAvatarIndex];
    }

    // ─────────────────────────────────────────────
    // Registro del Controller
    // ─────────────────────────────────────────────
    /**
     * Asigna el Controller de esta pantalla. Conecta el botón "SIGUIENTE" al
     * método del Controller.
     *
     * @param controller El controller que manejará las acciones de esta View.
     */
    public void setController(RegisterController controller) {
        this.controller = controller;

        // Conectar el botón continuar al controller
        BtnContinuar.addActionListener(
                e -> controller.onContinueClicked()
        );

        // También permitir presionar Enter en el campo de nombre
        campoUsuario.addActionListener(
                e -> controller.onContinueClicked()
        );
    }

}
