package Vistas;

import Controles.GameModeController;
import java.awt.event.ActionListener;
import Controles.LobbyController;

/**
 *
 * @author Héctor Javier Alonso Zaragoza
 * @author Alejandro Rodríguez Lugo
 * @author Katia Ximena Navarez Espinoza
 * @author Luis Carlos Manjarrez Gonzalez
 */
public class ModoJuego extends javax.swing.JPanel {

    private GameModeController controller;

    /**
     * Creates new form ModoJuego
     */
    public ModoJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelNombreU = new javax.swing.JLabel();
        labelAvatar = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnCrearSala = new javax.swing.JButton();
        BtnUnirsePartida = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 239, 225));
        setMaximumSize(new java.awt.Dimension(943, 613));
        setMinimumSize(new java.awt.Dimension(943, 613));
        setPreferredSize(new java.awt.Dimension(943, 613));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Elige un modo de juego");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 540, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNO_Log_pequenho.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 130));

        labelNombreU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(labelNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 110, 30));

        labelAvatar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(labelAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 100, 80));

        BtnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 130, 40));

        BtnCrearSala.setBackground(new java.awt.Color(0, 0, 51));
        BtnCrearSala.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnCrearSala.setForeground(new java.awt.Color(255, 255, 255));
        BtnCrearSala.setText("Crear Sala");
        add(BtnCrearSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 240, 220));

        BtnUnirsePartida.setBackground(new java.awt.Color(0, 0, 51));
        BtnUnirsePartida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnUnirsePartida.setForeground(new java.awt.Color(255, 255, 255));
        BtnUnirsePartida.setText("Unirse a Partida");
        add(BtnUnirsePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 240, 220));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCancelar;
    public javax.swing.JButton BtnCrearSala;
    public javax.swing.JButton BtnUnirsePartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel labelAvatar;
    public javax.swing.JLabel labelNombreU;
    // End of variables declaration//GEN-END:variables

    public void listenerCrearSala(ActionListener listener) {
        BtnCrearSala.addActionListener(listener);
    }

    public void listenerBtnCancelar(ActionListener listener) {
        BtnCancelar.addActionListener(listener);
    }

    public void setController(GameModeController controller) {
        this.controller = controller;
        BtnCrearSala.addActionListener(
                e -> controller.onContinueClicked()
        );
    }

}
